### ISSUE TITLE
Can I get eyeball mesh model after request?

### ISSUE THREAD

**Issue by hengfei-wang** [steliosploumpis/Universal_Head_3DMM#2]
I want to use the eyeball mesh model with texture in my research. After request, can I use images to fit the model and get the eyeball mesh model?

**Comment by steliosploumpis** [comment]
Currently we do not provide the textures for UHM. We make publicly available the shape models only. In order to fit the model you need to use your own method/algorithm to perform eyeball mesh reconstruction.

**Comment by hengfei-wang** [comment]
Ok, thank you!
